package com.levi.algorithm_practice.testdisruptor.perf;

public enum LogTypeEnum {
    COMMLOGPROCESS, COMMLOGWRITER,COMMLOGWRITERPROTO,PERFLOGWRITER, CONNECTIONLOGMAN, DBDEBUGPRINTER, FASTEXLOG,
    ORDERPUSHLOGPROCESS, QUOTATIONLOGPROCESS, RETURNPUSHLOGPROCESS, RETURNRECEIVERLOGPROCESS,
    RISKLOGPROCESS, TRADEDATALOGPROCESS;
}
